variables:
    NODE_VERSION: '22'
    LIBRARY_NG: 'kles-material-table-v2'

stages:
    - prepare
    - quality
    - security
    - build
    - release
    - publish

include:
    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-secrets/vault-kv-export@1.2.0
      inputs:
          job_name: 'nexus_creds'
          stage: 'prepare'
          vault_role: gitlab-nexus
          kv_mount: ci
          secret_path: nexus
          mappings: |
              NPM_TOKEN=token

    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-secrets/vault-kv-export@1.2.0
      inputs:
          job_name: 'npmjs_creds'
          stage: 'prepare'
          vault_role: gitlab-npmjs
          kv_mount: ci
          secret_path: npmjs
          mappings: |
              NPM_TOKEN=token

    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-security/gitleaks-scan@1.1.0
      inputs:
          stage: 'quality'

    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-node/lint@1.3.0
      inputs:
          node_version: $NODE_VERSION
          stage: 'quality'

    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-security/trivy-fs@1.1.0
      inputs:
          stage: 'security'

    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-node/build@1.4.0
      inputs:
          job_name: 'build'
          stage: 'build'
          node_version: $NODE_VERSION
          auth_token: $NPM_TOKEN
          npm_install_args: '--legacy-peer-deps'
          build_command: >-
              echo "Building Angular library: $LIBRARY_NG";
              npm run build -- "$LIBRARY_NG" --configuration production
          needs:
              - job: nexus_creds
              - job: lint
                optional: true
              - job: trivy-fs
                optional: true
              - job: gitleaks-scan
                optional: true

    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-node/release@1.3.0
      inputs:
          node_version: $NODE_VERSION
          stage: 'release'
          needs:
              - build

    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-node/publish@1.3.0
      inputs:
          job_name: 'publish_internal'
          stage: 'publish'
          node_version: $NODE_VERSION
          registry_url: $NPM_PRIVATE_REGISTRY_3KLES
          auth_token: $NPM_TOKEN
          working_dir: 'dist/$LIBRARY_NG'
          needs:
              - job: nexus_creds
              - job: build
                artifacts: true

    - component: $CI_SERVER_FQDN/cicd/ci-components/ci-components-node/publish@1.3.0
      inputs:
          job_name: 'publish_public'
          stage: 'publish'
          node_version: $NODE_VERSION
          auth_token: $NPM_TOKEN
          package_access: 'public'
          working_dir: 'dist/$LIBRARY_NG'
          needs:
              - job: npmjs_creds
              - job: build
                artifacts: true
