repositoryUrl: 'http://gitlab.3kles.local/3kles/lib/angular/material/klesmaterialtable-dev.git'

branches:
    - main
    - name: alpha
      prerelease: alpha
      channel: alpha
    - name: hotfix/**
      prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/changelog'
    - - '@semantic-release/npm'
      - npmPublish: false # Ne publie pas sur npm
        pkgRoot: . # Dossier racine du package
    - - '@semantic-release/exec'
      - prepareCmd: >-
            echo "Updating Angular library version to ${nextRelease.version}" &&
            npm pkg set version="${nextRelease.version}" --prefix "projects/$LIBRARY_NG"
    - - '@semantic-release/git'
      - assets:
            - package.json
            - package-lock.json
            - projects/*/package.json
            - CHANGELOG.md
        message: |
            chore(release): v${nextRelease.version}

            🔖 Version: ${nextRelease.version}
            📦 Release type: ${nextRelease.type}

            📝 Notes de version:
            ${nextRelease.notes}
    - '@semantic-release/gitlab'
